package com.example.prova.view;

import com.example.prova.model.Libro;
import com.example.prova.model.Ordine;
import com.example.prova.model.Utente;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class AccountResponsabile extends javax.swing.JPanel {

    /**
     * Creates new form AccountResponsabile
     */
    private List<Ordine> ordini = new ArrayList<>();
    private List<Utente> utenti = new ArrayList<>();
    private MainWindow main;

    public AccountResponsabile(MainWindow main) {

        this.main = main;
        initComponents();
        updateTableOrdini();
        updateTableUtenti();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        titoloText = new javax.swing.JTextField();
        autoreText = new javax.swing.JTextField();
        casaEditriceText = new javax.swing.JTextField();
        annoText = new javax.swing.JTextField();
        prezzoText = new javax.swing.JTextField();
        isbnText = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descrizioneText = new javax.swing.JTextArea();
        genereBox = new javax.swing.JComboBox<>();
        aggiungiLibroButton = new javax.swing.JButton();
        aggiornaClassificheButton = new javax.swing.JButton();
        statoBoc = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        puntiText = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "ID", "Email", "Stato"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String [] {
                        "Email", "LibroCardPunti"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Titolo:");

        jLabel2.setText("Autore:");

        jLabel3.setText("Casa Editrice");

        jLabel4.setText("Anno");

        jLabel5.setText("Genere");

        jLabel6.setText("Descrizione:");

        jLabel7.setText("Prezzo:");

        jLabel9.setText("ISBN:");





        descrizioneText.setColumns(20);
        descrizioneText.setRows(5);
        jScrollPane3.setViewportView(descrizioneText);

        genereBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NARRAZIONE", "AVVENTURA", "NOVITA", "RAGAZZI" }));

        aggiungiLibroButton.setText("Aggiungi Libro");
        aggiungiLibroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiLibroButtonActionPerformed(evt);
            }
        });

        aggiornaClassificheButton.setText("Aggiorna Classifiche");
        aggiornaClassificheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiornaClassificheButtonActionPerformed(evt);
            }
        });

        statoBoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN PREPARZIONE", "SPEDITO", "CONSEGNATO" }));

        jButton1.setText("Modifica");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Punti");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(aggiornaClassificheButton)
                                                                .addGap(31, 31, 31)
                                                                .addComponent(aggiungiLibroButton)
                                                                .addGap(29, 29, 29))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel6)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jScrollPane3))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel7)
                                                                                        .addComponent(jLabel9))
                                                                                .addGap(0, 0, Short.MAX_VALUE))))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addComponent(statoBoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(63, 63, 63)
                                                                .addComponent(jButton1)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(titoloText, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(autoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(casaEditriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(annoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(80, 80, 80)
                                                                .addComponent(isbnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel8)
                                                                        .addComponent(jLabel5))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(puntiText)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(prezzoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(genereBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {annoText, autoreText, casaEditriceText, isbnText, prezzoText, titoloText});

        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(titoloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(autoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(casaEditriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(annoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(1, 1, 1)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(statoBoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabel5)
                                                                .addGap(1, 1, 1))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(puntiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(genereBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(prezzoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel7))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(isbnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel9))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(65, 65, 65)
                                                                .addComponent(jLabel6)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(aggiornaClassificheButton)
                                                        .addComponent(aggiungiLibroButton))))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>




    //MODIFICA BUTTON
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        //modifica l'ordine selezionato e aggiorna la tabella ordini
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        int id = (int) dm.getValueAt(jTable1.getSelectedRow(), 0);
        Ordine modificato = new Ordine();
        try{
            modificato = main.getController().getOrdineController().findById(id);
            modificato.setStato(statoBoc.getSelectedItem().toString());
            main.getController().getOrdineController().save(modificato);
            JOptionPane.showMessageDialog(null, "Ordine modificato!");
            updateTableOrdini();
        }catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Qualcosa è andato storto!");
        }


    }

    private void aggiornaClassificheButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            main.getController().getLibroController().aggiornaClassifiche(main.getUtenteCorrente(), "NARRAZIONE");

            main.getController().getLibroController().aggiornaClassifiche(main.getUtenteCorrente(), "AVVENTURA");
            main.getController().getLibroController().aggiornaClassifiche(main.getUtenteCorrente(), "NOVITA");
            main.getController().getLibroController().aggiornaClassifiche(main.getUtenteCorrente(), "RAGAZZI");
            JOptionPane.showMessageDialog(null, "Classifiche aggiornate!");
        }catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Qualcosa è andato storto");
        }
    }


    private void aggiungiLibroButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String titolo ="";
        String autore ="";
        String casa = "";
        int anno = 0;
        String genere ="";
        double prezzo = 0;
        String isbn ="";
        String descrizione ="";
        int punti = 0;
        try{
            titolo = titoloText.getText();
            autore = autoreText.getText();
            casa = casaEditriceText.getText();
            anno = Integer.parseInt(annoText.getText());
            genere = genereBox.getSelectedItem().toString();
            prezzo= Double.parseDouble(prezzoText.getText());
            isbn = isbnText.getText();
            descrizione = descrizioneText.getText();
            punti = Integer.parseInt(puntiText.getText());
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Campi inseriti non corretti");
            return;
        }
        Libro nuovo = new Libro();
        nuovo.setTitolo(titolo);
        nuovo.setAutore(autore);
        nuovo.setCasaEditrice(casa);
        nuovo.setAnno(anno);
        nuovo.setGenere(genere);
        nuovo.setPrezzo(prezzo);
        nuovo.setIsbn(isbn);
        nuovo.setDescrizione(descrizione);
        nuovo.setPunti(punti);
        nuovo.setTempo(0);
        nuovo.setVendite(0);
        try{
            main.getController().getLibroController().aggiungi(nuovo);
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Impossibile aggiungere il libro");
            return;
        }
        JOptionPane.showMessageDialog(null, "Libro aggiunto!");
        main.setLibri(main.getController().getLibroController().findAll());
        main.updateTable();


    }

    private void updateTableOrdini(){
        ordini = main.getController().getOrdineController().findAll();
        int count = 0;
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        for(Ordine tmp: ordini){
            dm.addRow(new Object[]{tmp.getIdentificativo()});
            jTable1.setValueAt(tmp.getIdentificativo(), count,0);
            jTable1.setValueAt(tmp.getEmail(), count,1);
            jTable1.setValueAt(tmp.getStato(), count,2);

            count++;
        }
    }

    private void updateTableUtenti(){
        utenti = main.getController().getUtenteController().findUtentiRegistrati("REGISTRATO");
        int count = 0;
        DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        for(Utente tmp: utenti){
            dm.addRow(new Object[]{tmp.getEmail()});
            jTable2.setValueAt(tmp.getEmail(), count,0);
            jTable2.setValueAt(tmp.getLibroCardPunti(), count,1);
            count++;
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JButton aggiornaClassificheButton;
    private javax.swing.JButton aggiungiLibroButton;
    private javax.swing.JTextField annoText;
    private javax.swing.JTextField autoreText;
    private javax.swing.JTextField casaEditriceText;
    private javax.swing.JTextArea descrizioneText;
    private javax.swing.JComboBox<String> genereBox;
    private javax.swing.JTextField isbnText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField prezzoText;
    private javax.swing.JTextField puntiText;
    private javax.swing.JComboBox<String> statoBoc;
    private javax.swing.JTextField titoloText;
}
